# Generated by Django 4.2 on 2023-06-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='product_category',
            new_name='category',
        ),
    ]
