# Generated by Django 4.2 on 2023-06-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_ct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ct',
        ),
    ]
